let str1 = "Sendhil Kumar";
let str11 = str1.toLowerCase();
console.log(str11);
str11 = str1.toUpperCase();
console.log(str11);
str11 = str1.charAt(3);
console.log(str11);
str11 = str1.indexOf("Kumar",5);
console.log(str11);
str11 = str1.concat(" Dayanithi");
console.log(str11);
str11 = str1.includes("dhil",3);
console.log(str11);
str11 = str1.split(" ");
console.log(str11);
str11 = str1.substr(2,7);
console.log(str11);
str11 = str1.search("Dayanithi");
console.log(str11);
str11 = str1.trim();
console.log(str11);
console.log('------------->------------------>------------>');
let str2 = "Nandhini";
let str12 = str2.toLowerCase();
console.log(str12);
str12 = str2.toUpperCase();
console.log(str12);
str12 = str2.charAt(3);
console.log(str12);
str12 = str1.indexOf("and",5);
console.log(str12);
str12 = str2.concat("Dayanithi");
console.log(str12);
str12 = str2.includes("ni",3);
console.log(str12);
str12 = str2.split("i");
console.log(str12);
str12 = str2.substr(2,7);
console.log(str12);
str12 = str2.search("Dayanithi");
console.log(str12);
str12 = str2.trim();
console.log(str12);
console.log('------------->------------------>------------>');
let str3 = "institute of Road and Transport Technology";
let str13 = str3.toLowerCase();
console.log(str13);
str13 = str3.toUpperCase();
console.log(str13);
str13 = str3.charAt(7);
console.log(str13);
str13 = str3.indexOf("and",5);
console.log(str13);
str13 = str3.concat("college");
console.log(str13);
str13 = str3.includes("Road",3);
console.log(str13);
str13 = str3.split(" ");
console.log(str13);
str13 = str3.substr(2,7);
console.log(str13);
str13 = str3.search("of");
console.log(str13);
str13 = str3.trim();
console.log(str13);
console.log('------------->------------------>------------>');
let str4 = "Government Higher Secondary School";
let str14 = str4.toLowerCase();
console.log(str14);
str14 = str4.toUpperCase();
console.log(str14);
str14 = str4.charAt(3);
console.log(str14);
str14 = str4.indexOf("and",5);
console.log(str14);
str14 = str4.concat("School");
console.log(str14);
str14 = str4.includes("Hi",3);
console.log(str14);
str14 = str4.split("o");
console.log(str14);
str14 = str4.substr(2,7);
console.log(str14);
str14 = str4.search("Higher");
console.log(str14);
str14 = str4.trim();
console.log(str14);
console.log('------------->------------------>------------>');
let str5 = "Vadamathimangalam";
let str15 = str5.toLowerCase();
console.log(str15);
str15 = str5.toUpperCase();
console.log(str15);
str15 = str5.charAt(3);
console.log(str14);
str15 = str5.indexOf("ma",5);
console.log(str15);
str15 = str5.concat("School");
console.log(str15);
str15 = str5.includes("mathi",3);
console.log(str15);
str15 = str5.split("a");
console.log(str15);
str15 = str5.substr(2,7);
console.log(str15);
str15 = str5.search("vada");
console.log(str15);
str15 = str5.trim();
console.log(str15);
console.log('------------->------------------>------------>');
let str6 = "M.Kumaran Son Of Mahalakshmi";
let str16 = str6.toLowerCase();
console.log(str16);
str16 = str6.toUpperCase();
console.log(str16);
str16 = str6.charAt(3);
console.log(str16);
str16 = str6.indexOf("ha",5);
console.log(str16);
str16 = str6.concat("School");
console.log(str16);
str16 = str6.includes("lakshmi",3);
console.log(str16);
str16 = str6.split("son");
console.log(str16);
str16 = str6.substr(2,7);
console.log(str16);
str16 = str6.search("of");
console.log(str16);
str16 = str6.trim();
console.log(str16);
console.log('------------->------------------>------------>');
let str7 = "Vedha Daya";
let str17 = str7.toLowerCase();
console.log(str17);
str17 = str7.toUpperCase();
console.log(str17);
str17 = str7.charAt(3);
console.log(str17);
str17 = str7.indexOf("dha",5);
console.log(str17);
str17 = str7.concat("School");
console.log(str17);
str17 = str7.includes("ya",3);
console.log(str17);
str17 = str7.split("a");
console.log(str17);
str17 = str7.substr(2,7);
console.log(str17);
str17 = str7.search("e");
console.log(str17);
str17 = str7.trim();
console.log(str17);
console.log('------------->------------------>------------>');
let str8 = "Muthu Pandiyan";
let str18 = str8.toLowerCase();
console.log(str18);
str18 = str8.toUpperCase();
console.log(str18);
str18 = str8.charAt(3);
console.log(str18);
str18 = str8.indexOf("pandi",5);
console.log(str18);
str18 = str8.concat("chandru");
console.log(str18);
str18 = str8.includes("yan",3);
console.log(str18);
str18 = str8.split("th");
console.log(str18);
str18 = str8.substr(2,7);
console.log(str18);
str18 = str8.search("di");
console.log(str18);
str18 = str8.trim();
console.log(str18);
console.log('------------->------------------>------------>');
let str9 = "Akash Elango";
let str19 = str9.toLowerCase();
console.log(str19);
str19 = str9.toUpperCase();
console.log(str19);
str19 = str9.charAt(3);
console.log(str19);
str19 = str9.indexOf("g0",5);
console.log(str19);
str19 = str9.concat("School");
console.log(str19);
str19 = str9.includes("El",3);
console.log(str19);
str19 = str9.split(" ");
console.log(str19);
str19 = str9.substr(2,7);
console.log(str19);
str19 = str9.search("sh");
console.log(str19);
str19 = str9.trim();
console.log(str19);
console.log('------------->------------------>------------>');
