const places = ['Thiruvannamalai','Bangalore','Erode','Salem'];
const isArray = Array.isArray(places);
console.log(isArray);
console.log(typeof places);
const hadElement = places.includes('kerala');
console.log(hadElement);
const searching = places.includes('salem',2);
console.log(searching);
const addElement = places.push('Andhra','kerala');
console.log(addElement);
console.log(places);
const removeElement = places.pop();
console.log(removeElement);
console.log(places);
const add = places.unshift('karnataka','TamilNadu');
console.log(add);
console.log(places);
const remove = places.shift();
console.log(remove);
console.log(places);
const adding = places.splice(2,2,'Hyderabad','Delhi');
console.log(adding);
console.log(places);
const newArray = places.slice(1,5);
console.log(newArray);
const index = places.indexOf('Thiruvannamalai',1);
console.log(index);
const joining = places.join('~~');
console.log(joining);
console.log('================================================================');
const items = ['lipstick','Nailpolish','Eyeliner','ring'];
const isArray1 = Array.isArray(items);
console.log(isArray1);
console.log(typeof items);
const hadElement1 = items.includes('Necklace');
console.log(hadElement1);
const searching1 = items.includes('ring',2);
console.log(searching1);
const addElement1 = items.push('Anklet','Earring');
console.log(addElement1);
console.log(items);
const removeElement1 = items.pop();
console.log(removeElement1);
console.log(items);
const add1 = items.unshift('Bangles','Bindhi');
console.log(add1);
console.log(items);
const remove1 = places.shift();
console.log(remove1);
console.log(items);
const adding1 = places.splice(2,2,'chain','Maschara');
console.log(adding1);
console.log(items);
const newArray1 = items.slice(1,5);
console.log(newArray1);
const index1 = places.indexOf('lipstick',1);
console.log(index1);
const joining1 = items.join('~~');
console.log(joining1);
console.log('================================================================');
const car = ['Audi','Benz','ferrari','jaguar'];
const isArray2 = Array.isArray(car);
console.log(isArray2);
console.log(typeof car);
const hadElement2 = car.includes('Benz');
console.log(hadElement2);
const searching2 = car.includes('jaguar',2);
console.log(searching2);
const addElement2 = car.push('Anklet','Earring');
console.log(addElement2);
console.log(car);
const removeElement2 = car.pop();
console.log(removeElement2);
console.log(car);
const add2 = car.unshift('tata','ambani');
console.log(add2);
console.log(car);
const remove2 = car.shift();
console.log(remove2);
console.log(car);
const adding2 = car.splice(2,0,'hyundai','Mahendra');
console.log(adding2);
console.log(car);
const newArray2 = car.slice(1,5);
console.log(newArray2);
const index2 = car.indexOf('ferrari',1);
console.log(index2);
const joining2 = car.join('~~');
console.log(joining2);
console.log('================================================================');
const friends = ['Nandhini','Mohana','Logu','viji'];
const isArray3 = Array.isArray(friends);
console.log(isArray3);
console.log(typeof friends);
const hadElement3 = friends.includes('Logu');
console.log(hadElement3);
const searching3 = friends.includes('viji',2);
console.log(searching3);
const addElement3 = friends.push('Malathi','Santhiya');
console.log(addElement3);
console.log(friends);
const removeElement3 = friends.pop();
console.log(removeElement3);
console.log(friends);
const add3 = friends.unshift('Manogari','Priya');
console.log(add3);
console.log(friends);
const remove3 = friends.shift();
console.log(remove3);
console.log(friends);
const adding3 = friends.splice(2,0,'Gayathri','vinaya');
console.log(adding3);
console.log(friends);
const newArray3 = items.slice(1,5);
console.log(newArray3);
const index3 = friends.indexOf('Nandhini',1);
console.log(index3);
const joining3 = friends.join(':-)');
console.log(joining3);
console.log('================================================================');
const company = ['TCS','UST global','TesTYantra','CTS'];
const isArray4 = Array.isArray(company);
console.log(isArray4);
console.log(typeof company);
const hadElement4 = company.includes('CTS');
console.log(hadElement4);
const searching4 = company.includes('TCS',2);
console.log(searching4);
const addElement4 = company.push('AMI','HCL');
console.log(addElement4);
console.log(company);
const removeElement4 = company.pop();
console.log(removeElement4);
console.log(places);
const add4 = places.unshift('Wipro','TechMahindra');
console.log(add4);
console.log(company);
const remove4 = company.shift();
console.log(remove4);
console.log(company);
const adding4 = company.splice(2,0,'Gayathri','vinaya');
console.log(adding4);
console.log(company);
const newArray4 = company.slice(1,5);
console.log(newArray4);
const index4 = company.indexOf('Nandhini',1);
console.log(index4);
const joining4 = company.join(':::)');
console.log(joining4);
console.log('================================================================');
const mobile = ['Redmi','RealMe','Vivo','Samsung'];
const isArray5 = Array.isArray(mobile);
console.log(isArray5);
console.log(typeof mobile);
const hadElement5 = mobile.includes('Vivo');
console.log(hadElement5);
const searching5 = mobile.includes('Redmi',0);
console.log(searching5);
const addElement5 = mobile.push('AMI','HCL');
console.log(addElement5);
console.log(mobile);
const removeElement5 = mobile.pop();
console.log(removeElement5);
console.log(mobile);
const add5 = mobile.unshift('Nokia','Auis');
console.log(add5);
console.log(mobile);
const remove5 = mobile.shift();
console.log(remove5);
console.log(mobile);
const adding5 = mobile.splice(2,0,'lava','Moto');
console.log(adding5);
console.log(mobile);
const newArray5 = mobile.slice(1,5);
console.log(newArray5);
const index5 = mobile.indexOf('RealMe',1);
console.log(index5);
const joining5 = mobile.join(':::)');
console.log(joining5);
console.log('================================================================');
const transport = ['cycle','Bike','car','truck'];
const isArray6 = Array.isArray(transport);
console.log(isArray6);
console.log(typeof transport);
const hadElement6 = transport.includes('Vivo');
console.log(hadElement6);
const searching6 = transport.includes('truck',0);
console.log(searching6);
const addElement6 = transport.push('aeroplane','jet');
console.log(addElement6);
console.log(transport);
const removeElement6 = transport.pop();
console.log(removeElement6);
console.log(transport);
const add6 = transport.unshift('Nokia','Auis');
console.log(add6);
console.log(transport);
const remove6 = transport.shift();
console.log(remove6);
console.log(transport);
const adding6 = transport.splice(2,0,'flight','lorry');
console.log(adding6);
console.log(transport);
const newArray6 = transport.slice(1,5);
console.log(newArray6);
const index6 = transport.indexOf('Bike',1);
console.log(index6);
const joining6 = transport.join('-->)');
console.log(joining6);
console.log('================================================================');
const cartoon = ['Dora','Bheem','Mr.Bean','Roll No 21'];
const isArray7 = Array.isArray(cartoon);
console.log(isArray7);
console.log(typeof cartoon);
const hadElement7 = cartoon.includes('Dora');
console.log(hadElement7);
const searching7 = cartoon.includes('Bheem',0);
console.log(searching7);
const addElement7 = cartoon.push('little kirshna','Motu patlu');
console.log(addElement7);
console.log(cartoon);
const removeElement7 = cartoon.pop();
console.log(removeElement7);
console.log(cartoon);
const add7 = cartoon.unshift('Tom and Jerry','chin Shan');
console.log(add7);
console.log(cartoon);
const remove7 = cartoon.shift();
console.log(remove7);
console.log(cartoon);
const adding7 = cartoon.splice(2,0,'hungamma','pogo');
console.log(adding7);
console.log(cartoon);
const newArray7 = cartoon.slice(1,5);
console.log(newArray6);
const index7 = cartoon.indexOf('Bike',1);
console.log(index7);
const joining7 = cartoon.join('-->)');
console.log(joining7);
console.log('================================================================');
const course = ['java','sql','Html','css'];
const isArray8 = Array.isArray(course);
console.log(isArray8);
console.log(typeof course);
const hadElement8 = course.includes('css');
console.log(hadElement8);
const searching8 = course.includes('Bheem',0);
console.log(searching8);
const addElement8 = course.push('javascript','Nodejs');
console.log(addElement8);
console.log(course);
const removeElement8 = course.pop();
console.log(removeElement8);
console.log(course);
const add8 = course.unshift('Adv java','frameworks');
console.log(add8);
console.log(course);
const remove8 = course.shift();
console.log(remove8);
console.log(course);
const adding8 = course.splice(2,0,'spring','hibernet');
console.log(adding8);
console.log(course);
const newArray8 = course.slice(1,5);
console.log(newArray8);
const index8 = course.indexOf('Bike',1);
console.log(index8);
const joining8 = course.join('-->)');
console.log(joining8);
console.log('================================================================');
const movie = ['jayam','Arjun redddy','nota','dear comrade'];
const isArray9 = Array.isArray(movie);
console.log(isArray9);
console.log(typeof movie);
const hadElement9 = movie.includes('jayam');
console.log(hadElement9);
const searching9 = movie.includes('Bheem',0);
console.log(searching9);
const addElement9 = movie.push('M.kumaran','Aadai');
console.log(addElement9);
console.log(movie);
const removeElement9 = movie.pop();
console.log(removeElement9);
console.log(movie);
const add9 = movie.unshift('comali','bghil');
console.log(add9);
console.log(movie);
const remove9 = movie.shift();
console.log(remove9);
console.log(movie);
const adding9 = movie.splice(2,0,'KGF','Maveeran');
console.log(adding9);
console.log(movie);
const newArray9 = movie.slice(1,5);
console.log(newArray9);
const index9 = movie.indexOf('Bike',1);
console.log(index8);
const joining9 = movie.join('-->)');
console.log(joining9);
console.log('================================================================');